# Generated by Django 2.2.5 on 2021-07-11 23:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Leads', '0003_auto_20210711_2329'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='organization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Leads.UserProfile'),
            preserve_default=False,
        ),
    ]
