# Generated by Django 2.2.5 on 2021-07-17 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Leads', '0010_auto_20210715_2231'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='profile_pictures',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
